name: Deploy Uniswap Routing API

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@d3-inc'

      - name: Create .env file
        run: printf "%s" "${{ secrets.DOTENV }}" > .env

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install CDK CLI
        run: npm install -g aws-cdk@2.1029.0

      - name: Deploy CDK stack
        run: cdk deploy RoutingAPIStack
